# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'  
    packages:
      - libmagick++-dev

after_success:
  - Rscript -e 'covr::codecov()'
